import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import Header from "@/components/header";
import "./globals.css";
import { Toaster as Sonner } from "@/components/ui/sonner";
import AuthProvider from "@/context/authProvider";


const geistMono = Geist_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-geist-mono",
});



export const metadata: Metadata = {
  title: "TypeArena",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistMono.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          {children}
          <Sonner richColors expand={true} position="bottom-right" />
        </body>
      </AuthProvider>
    </html>
  );
}
